// User reducers
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOADING_USER = 'LOADING_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const CUSTOMER_INFO = 'CUSTOMER_INFO';
export const CUSTOMER_INFO_FAIL = 'CUSTOMER_INFO_FAIL';
export const CUSTOMER_BET_INFO = 'CUSTOMER_BET_INFO';
export const CUSTOMER_BET_INFO_FAIL = 'CUSTOMER_BET_INFO_FAIL';
export const DISPLAY_PROFILE = 'DISPLAY_PROFILE';
export const DISPLAY_MEMBERSHIP = 'DISPLAY_MEMBERSHIP';
export const RACE_STADIUM_INFO = 'RACE_STADIUM_INFO';
export const RACE_STADIUM_INFO_FAIL = 'RACE_STADIUM_INFO_FAIL';
export const RACE_INFO = 'RACE_INFO';
export const RACE_INFO_FAIL = 'RACE_INFO_FAIL';
export const BET_TRUE = 'BET_TRUE';
export const BET_FALSE = 'BET_FALSE';
export const SET_RACE_LOCATION = 'SET_RACE_LOCATION';
export const OPEN_ADD_FUND = 'OPEN_ADD_FUND';
export const CLOSE_ADD_FUND = 'CLOSE_ADD_FUND';
export const ADD_FUND = 'ADD_FUND';
